# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
highlighter:      pygments
highlight:        true

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            陈苑韬
tagline:          'Keep hungry, Keep foolish.'
description:      '你好，这里是陈苑韬的个人博客网站。'
url:              http://chenyuantao.github.io

author:
  name:           'chenyuantao'
  url:            https://github.com/chenyuantao

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : chenyuantao
