# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            陈苑韬
tagline:          'Stay hungry, Stay foolish.'
description:      '陈苑韬的个人技术博客.'
url:              http://chenyuantao.github.io

author:           
  name:           'chenyuantao'
  url:            https://github.com/chenyuantao

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : chenyuantao
